####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id$

TOP = ../..

all: makeharmonylib nc

include $(TOP)/Top.Makefile

RESULT = harmonize-plist
SOURCES = harmonize-plist.ml 

INCDIRS += $(SRCDIR) $(SRCDIR)/ubase
LIBS += harmony

include $(OCAMLMAKEFILE)


