####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id$ 

TOP = ..
include $(TOP)/Top.Makefile
SUBDIRS = $(ALLSUBDIRS)

all: buildsubdirs

