####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id: Makefile 413 2005-06-07 19:18:34Z bcpierce $

TOP = ../..

all: makeharmonylib nc

include $(TOP)/Top.Makefile

RESULT = harmonize-plist
SOURCES = harmonize-plist.ml 
LIBS += harmony

include $(OCAMLMAKEFILE)


