#!/bin/sh -x

if [ -z $1 ] 
then
  echo "usage: harmony-package arch";
  exit 1
fi

DIR="harmony-"`date "+20%y%m%d"`"-$1-binary"

svn export svn+ssh://jnfoster@halfdome.cis.upenn.edu/mnt/eclipse/plclub1/svnroot/harmony/trunk/
mv trunk $DIR
cd $DIR
omake
omake clean
cd ../
tar zcvf $DIR.tar.gz $DIR
#rm -fr $DIR
