####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id$

TOP = ../..
include $(TOP)/Top.Makefile

all: test

test::
	$(HARMONY) check -module Structuredtext -test-all

