####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
#                                                                  #
# Common Makefile infrastructure			           #
####################################################################

TOP = ../..
include $(TOP)/Top.Makefile

all: test

test::
	$(HARMONY) check -module Copy -test-all
