#####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
#                                                                  #
# Makefile - main Makefile for harmony                             #
#                                                                  #
# $Id$ #
#                                                                  #
#####################################################################

SRC = $(shell pwd)

RESULT = harmony
SOURCES = $(COMMON_SOURCES) harmony.ml 
OCAMLLDFLAGS = -linkpkg

include $(SRC)/Common.Makefile

