type token =
  | EOF of (Info.t)
  | STRING of (Info.t)
  | REGEXP of (Info.t)
  | DLENS of (Info.t)
  | KLENS of (Info.t)
  | SLENS of (Info.t)
  | RLENS of (Info.t)
  | CANONIZER of (Info.t)
  | STR of (Info.t * string)
  | IDENT of (Info.t * string)
  | CSET of (Info.t * string)
  | NSET of (Info.t * string)
  | INT of (Info.t * int)
  | LBRACE of (Info.t)
  | RBRACE of (Info.t)
  | LBRACK of (Info.t)
  | RBRACK of (Info.t)
  | LPAREN of (Info.t)
  | RPAREN of (Info.t)
  | LANGLE of (Info.t)
  | RANGLE of (Info.t)
  | ARROW of (Info.t)
  | DARROW of (Info.t)
  | LONGARROW of (Info.t)
  | LONGDARROW of (Info.t)
  | CREATE of (Info.t)
  | BEGIN of (Info.t)
  | END of (Info.t)
  | FUN of (Info.t)
  | LET of (Info.t)
  | IN of (Info.t)
  | TEST of (Info.t)
  | INTO of (Info.t)
  | SEMI of (Info.t)
  | COMMA of (Info.t)
  | DOT of (Info.t)
  | EQUAL of (Info.t)
  | COLON of (Info.t)
  | BACKSLASH of (Info.t)
  | STAR of (Info.t)
  | RLUS of (Info.t)
  | BANG of (Info.t)
  | BAR of (Info.t)
  | PLUS of (Info.t)
  | MINUS of (Info.t)
  | HAT of (Info.t)
  | TILDE of (Info.t)
  | AMPERSAND of (Info.t)
  | QMARK of (Info.t)
  | MATCH of (Info.t)
  | WITH of (Info.t)
  | GET of (Info.t)
  | PUT of (Info.t)
  | DOTGET of (Info.t)
  | DOTPUT of (Info.t)
  | DOTCREATE of (Info.t)
  | ERROR of (Info.t)

val top :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Rvalue.s Rvalue.Renv.t * (Rvalue.t * bool) Rvalue.Renv.t -> Rvalue.s Rvalue.Renv.t * (Rvalue.t * bool) Rvalue.Renv.t
