#!/bin/sh

FILE1=$1
FILE2=$2
ARCHIVE=$FILE1+$FILE2.harmony

BAK_SUFFIX=`date '+20%y%m%d-%H:%M:%S'`.bak

case $FILE1 in
  *.csv) LENS1=Prelude.id; EKEY1=csv;;
  *.xml) LENS1=Prelude.id; EKEY1=xml;;
  *) echo "$FILE1 must end with either .csv or .xml"; exit 1;;
esac

case $FILE2 in
  *.csv) LENS2=Prelude.id; EKEY2=csv;;
  *.xml) LENS2=Prelude.id; EKEY2=xml;;
  *) echo "$FILE2 must end with either .csv or .xml"; exit 1;;
esac

cp $FILE1 $FILE1.$BAK_SUFFIX
cp $FILE2 $FILE2.$BAK_SUFFIX
cp $ARCHIVE $ARCHIVE.$BAK_SUFFIX

echo "Synchronizing $FILE1:$EKEY1 using $LENS1 with $FILE2:$EKEY2 using $LENS2..."

harmony sync -schema Prelude.Any -archive $ARCHIVE:meta -lensar Prelude.id \
                                 -replica1 $FILE1:$EKEY1 -lensr1 $LENS1 \
                                 -replica2 $FILE2:$EKEY2 -lensr2 $LENS2 \
                                 -newarchive $ARCHIVE:meta \
                                 -newreplica1 $FILE1:$EKEY1 \
                                 -newreplica2 $FILE2:$EKEY2
