####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
#                                                                  #
# Makefile - main Makefile for harmony examples                    #
####################################################################

# $Id: Makefile 121 2005-05-05 00:19:32Z bcpierce $ 

# This is clunky and temporary: it should derive the list of subdirectories automatically 
# and automatically run tests and such in all of them...

all: test

test:
	make -C bookmarks test
