####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id: Makefile 121 2005-05-05 00:19:32Z bcpierce $ 

SUBDIRS = bookmarks Vcard 

TOP = ..
include $(TOP)/Top.Makefile

