####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id$ 

SUBDIRSCLEANONLY = bookmarks Concat Vcard VCF demo structuredtext

TOP = ..
include $(TOP)/Top.Makefile

