SRC := $(shell pwd)/../src

RESULT = visual
CLIBS = $(COMMON_CLIBS)
SOURCES = $(COMMON_SOURCES) ui_init.ml ui_common.ml ui_example.ml \
         ui_trace.ml ui_focal.ml callbacks.ml visual.ml 
INCDIRS := +lablgtk2
LIBS = lablgtk 

include $(SRC)/Common.Makefile

