####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

# $Id$ 

SUBDIRS = template

TOP = ..
include $(TOP)/Top.Makefile

all:

