val beginend_lens : Lens.t
val repeat_type_lens : Lens.t
val dayofweek_lens : Lens.t
val dayofmonth_lens : Lens.t
val parsedate_lens : Lens.t
val enddate_lens : Lens.t
val repeat_on_lens : Lens.t
val repeat_lens : Lens.t
val datebooklens : Lens.t
val rtype_lens : Lens.t
val dbk2ical_lens : Lens.t
