#!/bin/sh

cd $HOME/current/icalsync

init=

for i
  do case $i in
     -i)  init=yes ;;
     --init)  init=yes ;;
     *)   echo Unrecognized flag \'$i\' 
          exit 1
     esac
  done

###############################################################################

echo -n "Please sync palm, close iCal, and press return "
read 

JUNK=`ps auxww | grep "i[C]al.app"`;
if [ $? = "0" ]; then
  echo "iCal is running, please stop it first"
  echo $JUNK
  exit 1
fi

###############################################################################

date=`date +"20%y%m%d+%h%m"`
palmdb=DatebookDB.pdb
icaldb=Home.ics

palmpath="$HOME/Documents/Palm/Users/Benjamin C. Pierce/Backups/$palmdb"
palmtopath="$HOME/Documents/Palm/Users/Benjamin C. Pierce/Files to Install/$palmdb"
icalpath=$HOME/Library/Calendars/$icaldb 

if test $init; then
  echo Starting from scratch
  cp "$palmpath" .
  rm $icaldb
  rm cal.ali*
  rm *.harmony
  echo Tidied contents of directory:
  ls -l
else
  cp "$palmpath" .
  cp "$icalpath" .
  mkdir backups
  cp $palmdb backups/$date-$palmdb
  cp $icaldb backups/$date-$icaldb
fi

echo ~/current/harmony/src/harmony -replace -align cal.ali -backup=false "sync $palmdb(pdbk) $icaldb(iCal) as [appointments]"
     time ~/current/harmony/src/harmony -replace -align cal.ali -backup=false "sync $palmdb(pdbk) $icaldb(iCal) as [appointments]" 

if [ $? != "0" ]; then
  echo "Harmony exited abnormally"
  exit 1
fi

echo
echo "[Careful: if you do NOT commit, then there is a danger that the cal.ali and XXX.harmony "
echo "files are going to be out of date.  The icalsync script should be fixed!]"
echo
echo -n "Press return to commit "
read JUNK

# copy misc files to palm
topalm

cp $icaldb "$icalpath"
cp $palmdb "$palmtopath"

echo
echo "Harmony sync finished."
echo "Remember to hotsync palm again!"

open /Applications/iCal.app

