####################################################################
# The Harmony Project                                              #
# harmony@lists.seas.upenn.edu                                     #
####################################################################

TOP = ../..
include $(TOP)/Top.Makefile

RESULT = harmonize-basics

all: $(RESULT)

$(RESULT):
	ln -s $(SRCDIR)/harmony $(RESULT)

clean::
	rm -rf $(RESULT)

